### ISSUE TITLE
texts after "code block language identifier" will prevent beautification operation. 

### ISSUE THREAD

**Issue by YaoYYoung** [wiop93256/Simple-Code-Formmater#1]
First of all, nice plugin🥰. 

Secondly, here comes the problem:

I both use [Code Styler plugin](https://github.com/mayurankv/Obsidian-Code-Styler) to pretty my code blocks, which provides functions like code header, hyperlink, highlighting lines based on the first line information text after code block language identifier like `javascript` or `c++`. 

When I put the cursor in the codeblock like this, `Simple Code Formatter` cann not execute it. 

```c++ title:[代码 x5.1 二叉树先序遍历算法（迭代版 01）binnode_travpreorder_i1.h](https://dsa.cs.tsinghua.edu.cn/~deng/ds/src_link/bintree/binnode_travpreorder_i1.h.htm) red:🔴 orange:🟠 yellow:🟡 green:🟢 blue:🔵 purple:🟣 
template <typename T, typename VST> // 元素类型、操作器
void travPre_I1( BinNodePosi<T> x, VST& visit ) { // 二叉树先序遍历算法（迭代版 01）
	Stack<BinNodePosi<T>> S; // 辅助栈
	if ( x ) S.push( x ); // 根节点入栈
	while ( !S.empty() ) { // 在栈变空之前反复循环
		x = S.pop(); visit( x->data ); // 弹出并访问当前节点，其非空孩子的入栈次序为先右后左
		if ( HasRChild( *x ) ) S.push( x->rc ); // 🟠优先将右孩子放入栈中
		if ( HasLChild( *x ) ) S.push( x->lc ); // 🟡然后将左孩子放入栈中
	}
}
```

![image](https://github.com/user-attachments/assets/92af7835-4442-4f21-a9ed-54783c4f4882)

But removed the information texts in first line, this codeblock can be executed. 

```c
template <typename T, typename VST> // 元素类型、操作器
void travPre_I1( BinNodePosi<T> x, VST& visit ) { // 二叉树先序遍历算法（迭代版 01）
	Stack<BinNodePosi<T>> S; // 辅助栈
	if ( x ) S.push( x ); // 根节点入栈
	while ( !S.empty() ) { // 在栈变空之前反复循环
		x = S.pop(); visit( x->data ); // 弹出并访问当前节点，其非空孩子的入栈次序为先右后左
		if ( HasRChild( *x ) ) S.push( x->rc ); // 🟠优先将右孩子放入栈中
		if ( HasLChild( *x ) ) S.push( x->lc ); // 🟡然后将左孩子放入栈中
	}
}
```

![image](https://github.com/user-attachments/assets/b83ff18c-3eb0-46bf-b069-8b397acd1dd7)

Now Simple-Code-Formmater plugin does not supported `c++` codeblocks instead of `c` codeblocks, which is not the principal problem.

**Comment by wiop93256** [comment]
好，我修复一下你说的问题。第一是，支持`Code Styler`的特殊`代码块头`。第二是，同时接受`C++`与`C`。

**Comment by wiop93256** [comment]
已更新在v1.1.0版本中
