### ISSUE TITLE
c#格式能否做修改？

### ISSUE THREAD

**Issue by SMyPresious** [wiop93256/Simple-Code-Formmater#5]
例：c#格式代码如下
private List<Color32> m_Colors = ListPool<Color32>.Get();
自动格式化后为：
private List < Color32 > m_Colors = ListPool < Color32 > .Get();
像类似的泛型方法可否保持原代码风格，不加如此多的空格？这样看起来是不是更整洁

**Comment by wiop93256** [comment]
好 有时间我看一下

**Comment by wiop93256** [comment]
请更新1.2.0版本

**Comment by SMyPresious** [comment]
感谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月10日(周二) 上午10:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wiop93256/Simple-Code-Formmater] c#格式能否做修改？ (Issue #5)




 
请更新1.2.0版本

**Comment by wiop93256** [comment]
不客气 我也是.NET开发
