### ISSUE TITLE
能不能支持自定义格式化配置

### ISSUE THREAD

**Issue by xcdh-lzj** [wiop93256/Simple-Code-Formmater#6]
<img width="377" alt="image" src="https://github.com/user-attachments/assets/d90a228f-fe74-4b7e-b1fd-ef3d8b3fd45c" />

这里缩进只有2个空格，我想java代码的话就4个空格，html或者json等其它的，就2个空格

希望加入这个功能，谢谢

**Comment by wiop93256** [comment]
Java传统代码风格是4个空格，我这边修改一下。

**Comment by wiop93256** [comment]
1.2.2已发布 请更新
